services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly-db-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=$POSTGRES_USER
      - POSTGRESQL_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRESQL_DATABASE=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app

  app:
    build: .
    depends_on:
      - db
    container_name: brevly-app-postgres
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - app

volumes:
  db:


networks:
  app:
    driver: bridge
